language: cpp
os:
  - linux
sudo: required
dist: trusty
before_install:
  - sudo apt-get install software-properties-common --yes
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
  - sudo apt-get update --yes
install:
  - sudo apt-get install cmake cmake-data --yes
script:
  - cmake . && cmake --build .
