language: cpp
os:
  - linux
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
  - sudo apt-get update
install:
  - sudo apt-get install cmake cmake-data
script:
  - mkdir build && cd build && cmake .. && cmake --build .
